name: Grading workflow

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  grade-learner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Grade exercise-publish-package activity
        id: events
        uses: ./.github/actions/local-action
        with:
          event_ctx: ${{toJSON(github.event)}}

      - name: Grading results
        uses: githubtraining/looking-glass-action@v1.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          feedback: ${{ steps.events.outputs.reports }}
